# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[➜](bold blue)"

[java]
disabled = true

[cmake]
disabled = true

[python]
disabled = true

[line_break]
disabled = true
