# Inserts a blank line between shell prompts
add_newline = false

command_timeout = 10000

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[V](bold green)"

[java]
disabled = true

[cmake]
disabled = true

[python]
disabled = true

[line_break]
disabled = true

[cmd_duration]
disabled = true
